import type { BloatwareApp } from '@shared/types'

export const PROMOTED_APPS: Omit<BloatwareApp, 'id' | 'size' | 'selected'>[] = [
  // Streaming / Media
  {
    name: 'Disney+',
    packageName: 'Disney.37853FC22B2CE',
    publisher: 'Disney',
    category: 'media',
    description: 'Streaming app — pre-installed promotion',
  },
  {
    name: 'Spotify',
    packageName: 'SpotifyAB.SpotifyMusic',
    publisher: 'Spotify',
    category: 'media',
    description: 'Music streaming — pre-installed promotion',
  },
  {
    name: 'TikTok',
    packageName: 'BytedancePte.Ltd.TikTok',
    publisher: 'ByteDance',
    category: 'media',
    description: 'Social media — pre-installed promotion',
  },
  {
    name: 'Netflix',
    packageName: '4DF9E0F8.Netflix',
    publisher: 'Netflix',
    category: 'media',
    description: 'Streaming app — pre-installed promotion',
  },
  {
    name: 'Amazon Prime Video',
    packageName: 'AmazonVideo.PrimeVideo',
    publisher: 'Amazon',
    category: 'media',
    description: 'Streaming app — pre-installed promotion',
  },
  {
    name: 'Hulu',
    packageName: 'HuluLLC.HuluPlus',
    publisher: 'Hulu',
    category: 'media',
    description: 'Streaming app — pre-installed promotion',
  },
  {
    name: 'Pandora',
    packageName: 'PandoraMediaInc.29680B314EFC2',
    publisher: 'Pandora',
    category: 'media',
    description: 'Music streaming — pre-installed promotion',
  },
  {
    name: 'iHeartRadio',
    packageName: 'ClearChannelRadioDigital.iHeartRadio',
    publisher: 'iHeartMedia',
    category: 'media',
    description: 'Radio streaming — pre-installed promotion',
  },
  {
    name: 'TuneIn Radio',
    packageName: 'TuneIn.TuneInRadio',
    publisher: 'TuneIn',
    category: 'media',
    description: 'Radio streaming — pre-installed promotion',
  },
  {
    name: 'Plex',
    packageName: 'CAF9E577.Plex',
    publisher: 'Plex',
    category: 'media',
    description: 'Media server client — pre-installed promotion',
  },
  {
    name: 'Sling TV',
    packageName: 'SlingTV.SlingTV',
    publisher: 'Sling TV',
    category: 'media',
    description: 'Live TV streaming — pre-installed promotion',
  },
  {
    name: 'Shazam',
    packageName: 'ShazamEntertainmentLtd.Shazam',
    publisher: 'Apple',
    category: 'media',
    description: 'Music recognition — pre-installed promotion',
  },
  {
    name: 'Flipboard',
    packageName: 'Flipboard.Flipboard',
    publisher: 'Flipboard',
    category: 'media',
    description: 'News aggregator — pre-installed promotion',
  },

  // Social / Communication
  {
    name: 'Instagram',
    packageName: 'Facebook.InstagramBeta',
    publisher: 'Meta',
    category: 'communication',
    description: 'Social media — pre-installed promotion',
  },
  {
    name: 'Facebook',
    packageName: 'Facebook.Facebook',
    publisher: 'Meta',
    category: 'communication',
    description: 'Social media — pre-installed promotion',
  },
  {
    name: 'LinkedIn',
    packageName: '7EE7776C.LinkedInforWindows',
    publisher: 'LinkedIn',
    category: 'communication',
    description: 'Social media — pre-installed promotion',
  },
  {
    name: 'Twitter',
    packageName: '9E2F88E3.Twitter',
    publisher: 'X Corp',
    category: 'communication',
    description: 'Social media — pre-installed promotion',
  },
  {
    name: 'Viber',
    packageName: 'Viber.Viber',
    publisher: 'Viber',
    category: 'communication',
    description: 'Messaging app — pre-installed promotion',
  },
  {
    name: 'Pinterest',
    packageName: 'Pinterest.Pinterest',
    publisher: 'Pinterest',
    category: 'communication',
    description: 'Visual discovery platform — pre-installed promotion',
  },

  // Pre-installed games
  {
    name: 'Candy Crush Saga',
    packageName: 'king.com.CandyCrushSaga',
    publisher: 'King',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Candy Crush Friends',
    packageName: 'king.com.CandyCrushFriends',
    publisher: 'King',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Bubble Witch 3',
    packageName: 'king.com.BubbleWitch3Saga',
    publisher: 'King',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'March of Empires',
    packageName: 'Gameloft.MarchofEmpires',
    publisher: 'Gameloft',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Asphalt 8',
    packageName: 'Gameloft.Asphalt8Airborne',
    publisher: 'Gameloft',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Caesars Slots',
    packageName: 'PlaytikaSantaMonica.CaesarsSlotsFreeCasino',
    publisher: 'Playtika',
    category: 'gaming',
    description: 'Pre-installed casino game',
  },
  {
    name: 'Cooking Fever',
    packageName: 'JEGOROVVLADIMIR.46390A297A2C4',
    publisher: 'Nordcurrent',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Disney Magic Kingdoms',
    packageName: 'GameloftSA.DisneyMagicKingdoms',
    publisher: 'Gameloft',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'FarmVille 2',
    packageName: 'Zynga.FarmVille2CountryEscape',
    publisher: 'Zynga',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Hidden City',
    packageName: 'G5Entertainment.HiddenCity',
    publisher: 'G5',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Royal Revolt',
    packageName: 'flaaboronlineGmbH.RoyalRevolt2',
    publisher: 'flaregames',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Angry Birds 2',
    packageName: 'RovioEntertainmentLtd.AngryBirds2',
    publisher: 'Rovio',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Township',
    packageName: 'PlayrixTownship.Township',
    publisher: 'Playrix',
    category: 'gaming',
    description: 'Pre-installed city-building game with microtransactions',
  },
  {
    name: 'Gardenscapes',
    packageName: 'PlayrixGardenscapes.Gardenscapes',
    publisher: 'Playrix',
    category: 'gaming',
    description: 'Pre-installed puzzle game with microtransactions',
  },
  {
    name: 'Royal Match',
    packageName: 'Dream3D.RoyalMatch',
    publisher: 'Dream3D',
    category: 'gaming',
    description: 'Pre-installed puzzle game with microtransactions',
  },
  {
    name: 'World of Tanks Blitz',
    packageName: 'Wargaming.Net.WorldOfTanksBlitz',
    publisher: 'Wargaming',
    category: 'gaming',
    description: 'Pre-installed tank game with microtransactions',
  },
  {
    name: 'Crossout',
    packageName: 'TargemGames.Crossout',
    publisher: 'Targem',
    category: 'gaming',
    description: 'Pre-installed vehicle combat game',
  },

  // Utility
  {
    name: 'Duolingo',
    packageName: 'D5EA27B7.Duolingo-LearnLanguagesforFree',
    publisher: 'Duolingo',
    category: 'utility',
    description: 'Language learning — pre-installed promotion',
  },
  {
    name: 'Adobe Photoshop Express',
    packageName: 'AdobeSystemsIncorporated.AdobePhotoshopExpress',
    publisher: 'Adobe',
    category: 'utility',
    description: 'Photo editor — pre-installed promotion',
  },
  {
    name: 'Autodesk SketchBook',
    packageName: 'AutodeskSketchBook.SketchBook',
    publisher: 'Autodesk',
    category: 'utility',
    description: 'Drawing app — pre-installed promotion',
  },
  {
    name: 'Drawboard PDF',
    packageName: 'Drawboard.DrawboardPDF',
    publisher: 'Drawboard',
    category: 'utility',
    description: 'PDF editor — pre-installed promotion',
  },
  {
    name: 'Fitbit',
    packageName: 'Fitbit.FitbitCoach',
    publisher: 'Fitbit',
    category: 'utility',
    description: 'Fitness tracker — pre-installed promotion',
  },
  {
    name: 'PicsArt',
    packageName: 'PicsArt-PhotoStudio.PicsArt-PhotoStudio',
    publisher: 'PicsArt',
    category: 'utility',
    description: 'Photo editor — pre-installed promotion',
  },
  {
    name: 'Amazon',
    packageName: 'AmazonMobileLLC.AmazonShopping',
    publisher: 'Amazon',
    category: 'utility',
    description: 'Shopping app — pre-installed promotion',
  },
  {
    name: 'WinZip',
    packageName: 'WinZipComputing.WinZipUniversal',
    publisher: 'WinZip',
    category: 'utility',
    description: 'Archive tool — free alternatives available',
  },
  {
    name: 'Kahoot!',
    packageName: 'Kahoot.Kahoot',
    publisher: 'Kahoot',
    category: 'utility',
    description: 'Quiz platform — pre-installed promotion',
  },
  {
    name: 'Khan Academy',
    packageName: 'KhanAcademy.KhanAcademy',
    publisher: 'Khan Academy',
    category: 'utility',
    description: 'Educational videos — pre-installed promotion',
  },
  {
    name: 'Grammarly',
    packageName: 'Grammarly.Grammarly',
    publisher: 'Grammarly',
    category: 'utility',
    description: 'Writing assistant — pre-installed promotion',
  },
  {
    name: 'WPS Office',
    packageName: 'KingsoftOffice.WPSOffice',
    publisher: 'Kingsoft',
    category: 'utility',
    description: 'Office suite — pre-installed promotion, free version has ads',
  },
  {
    name: 'Booking.com',
    packageName: 'Booking.Booking',
    publisher: 'Booking Holdings',
    category: 'utility',
    description: 'Travel booking — pre-installed promotion',
  },
  {
    name: 'Tripadvisor',
    packageName: 'Tripadvisor.Tripadvisor',
    publisher: 'Tripadvisor',
    category: 'utility',
    description: 'Travel reviews — pre-installed promotion',
  },
]
