import type { BloatwareApp } from '@shared/types'

export const THIRD_PARTY_BLOATWARE: Omit<BloatwareApp, 'id' | 'size' | 'selected'>[] = [
  // OEM bloatware
  {
    name: 'Dell SupportAssist',
    packageName: 'DellInc.DellSupportAssistforPCs',
    publisher: 'Dell',
    category: 'oem',
    description: 'Dell support tool — heavy on resources and notifications',
  },
  {
    name: 'Dell Digital Delivery',
    packageName: 'DellInc.DellDigitalDelivery',
    publisher: 'Dell',
    category: 'oem',
    description: 'Dell software delivery service',
  },
  {
    name: 'Dell Command Update',
    packageName: 'DellInc.DellCommandUpdate',
    publisher: 'Dell',
    category: 'oem',
    description: 'Dell driver/BIOS updater',
  },
  {
    name: 'HP Smart',
    packageName: 'AD2F1837.HPPrinterControl',
    publisher: 'HP',
    category: 'oem',
    description: 'HP printer management — unnecessary without HP printer',
  },
  {
    name: 'HP Wolf Security',
    packageName: 'AD2F1837.HPWolfSecurity',
    publisher: 'HP',
    category: 'oem',
    description: 'HP security suite — redundant with Windows Defender',
  },
  {
    name: 'Lenovo Vantage',
    packageName: 'E046963F.LenovoCompanion',
    publisher: 'Lenovo',
    category: 'oem',
    description: 'Lenovo system management — heavy background services',
  },
  {
    name: 'Lenovo Now',
    packageName: 'E0469640.LenovoUtility',
    publisher: 'Lenovo',
    category: 'oem',
    description: 'Lenovo utility tool',
  },
  {
    name: 'McAfee',
    packageName: 'McAfee',
    publisher: 'McAfee',
    category: 'oem',
    description: 'Pre-installed antivirus — redundant with Windows Defender',
  },
  {
    name: 'Norton',
    packageName: 'Norton',
    publisher: 'NortonLifeLock',
    category: 'oem',
    description: 'Pre-installed antivirus — redundant with Windows Defender',
  },
  {
    name: 'WildTangent Games',
    packageName: 'WildTangentGames',
    publisher: 'WildTangent',
    category: 'oem',
    description: 'Pre-installed game platform — adware-like behavior',
  },

  // Common pre-installed apps
  {
    name: 'Disney+',
    packageName: 'Disney.37853FC22B2CE',
    publisher: 'Disney',
    category: 'media',
    description: 'Streaming app — pre-installed promotion',
  },
  {
    name: 'Spotify',
    packageName: 'SpotifyAB.SpotifyMusic',
    publisher: 'Spotify',
    category: 'media',
    description: 'Music streaming — pre-installed promotion',
  },
  {
    name: 'TikTok',
    packageName: 'BytedancePte.Ltd.TikTok',
    publisher: 'ByteDance',
    category: 'media',
    description: 'Social media — pre-installed promotion',
  },
  {
    name: 'Instagram',
    packageName: 'Facebook.InstagramBeta',
    publisher: 'Meta',
    category: 'communication',
    description: 'Social media — pre-installed promotion',
  },
  {
    name: 'Facebook',
    packageName: 'Facebook.Facebook',
    publisher: 'Meta',
    category: 'communication',
    description: 'Social media — pre-installed promotion',
  },
  {
    name: 'Candy Crush Saga',
    packageName: 'king.com.CandyCrushSaga',
    publisher: 'King',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Candy Crush Friends',
    packageName: 'king.com.CandyCrushFriends',
    publisher: 'King',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Bubble Witch 3',
    packageName: 'king.com.BubbleWitch3Saga',
    publisher: 'King',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'March of Empires',
    packageName: 'Gameloft.MarchofEmpires',
    publisher: 'Gameloft',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Asphalt 8',
    packageName: 'Gameloft.Asphalt8Airborne',
    publisher: 'Gameloft',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Caesars Slots',
    packageName: 'PlaytikaSantaMonica.CaesarsSlotsFreeCasino',
    publisher: 'Playtika',
    category: 'gaming',
    description: 'Pre-installed casino game',
  },
  {
    name: 'Cooking Fever',
    packageName: 'JEGOROVVLADIMIR.46390A297A2C4',
    publisher: 'Nordcurrent',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Disney Magic Kingdoms',
    packageName: 'GameloftSA.DisneyMagicKingdoms',
    publisher: 'Gameloft',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'FarmVille 2',
    packageName: 'Zynga.FarmVille2CountryEscape',
    publisher: 'Zynga',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Hidden City',
    packageName: 'G5Entertainment.HiddenCity',
    publisher: 'G5',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Royal Revolt',
    packageName: 'flaaboronlineGmbH.RoyalRevolt2',
    publisher: 'flaregames',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },

  // Third-party promoted apps
  {
    name: 'Netflix',
    packageName: '4DF9E0F8.Netflix',
    publisher: 'Netflix',
    category: 'media',
    description: 'Streaming app — pre-installed promotion',
  },
  {
    name: 'Amazon Prime Video',
    packageName: 'AmazonVideo.PrimeVideo',
    publisher: 'Amazon',
    category: 'media',
    description: 'Streaming app — pre-installed promotion',
  },
  {
    name: 'Hulu',
    packageName: 'HuluLLC.HuluPlus',
    publisher: 'Hulu',
    category: 'media',
    description: 'Streaming app — pre-installed promotion',
  },
  {
    name: 'LinkedIn',
    packageName: '7EE7776C.LinkedInforWindows',
    publisher: 'LinkedIn',
    category: 'communication',
    description: 'Social media — pre-installed promotion',
  },
  {
    name: 'Twitter',
    packageName: '9E2F88E3.Twitter',
    publisher: 'X Corp',
    category: 'communication',
    description: 'Social media — pre-installed promotion',
  },
  {
    name: 'Viber',
    packageName: 'Viber.Viber',
    publisher: 'Viber',
    category: 'communication',
    description: 'Messaging app — pre-installed promotion',
  },
  {
    name: 'Pandora',
    packageName: 'PandoraMediaInc.29680B314EFC2',
    publisher: 'Pandora',
    category: 'media',
    description: 'Music streaming — pre-installed promotion',
  },
  {
    name: 'iHeartRadio',
    packageName: 'ClearChannelRadioDigital.iHeartRadio',
    publisher: 'iHeartMedia',
    category: 'media',
    description: 'Radio streaming — pre-installed promotion',
  },
  {
    name: 'TuneIn Radio',
    packageName: 'TuneIn.TuneInRadio',
    publisher: 'TuneIn',
    category: 'media',
    description: 'Radio streaming — pre-installed promotion',
  },
  {
    name: 'Plex',
    packageName: 'CAF9E577.Plex',
    publisher: 'Plex',
    category: 'media',
    description: 'Media server client — pre-installed promotion',
  },
  {
    name: 'Sling TV',
    packageName: 'SlingTV.SlingTV',
    publisher: 'Sling TV',
    category: 'media',
    description: 'Live TV streaming — pre-installed promotion',
  },
  {
    name: 'Shazam',
    packageName: 'ShazamEntertainmentLtd.Shazam',
    publisher: 'Apple',
    category: 'media',
    description: 'Music recognition — pre-installed promotion',
  },
  {
    name: 'Duolingo',
    packageName: 'D5EA27B7.Duolingo-LearnLanguagesforFree',
    publisher: 'Duolingo',
    category: 'utility',
    description: 'Language learning — pre-installed promotion',
  },
  {
    name: 'Flipboard',
    packageName: 'Flipboard.Flipboard',
    publisher: 'Flipboard',
    category: 'media',
    description: 'News aggregator — pre-installed promotion',
  },
  {
    name: 'Adobe Photoshop Express',
    packageName: 'AdobeSystemsIncorporated.AdobePhotoshopExpress',
    publisher: 'Adobe',
    category: 'utility',
    description: 'Photo editor — pre-installed promotion',
  },
  {
    name: 'Autodesk SketchBook',
    packageName: 'AutodeskSketchBook.SketchBook',
    publisher: 'Autodesk',
    category: 'utility',
    description: 'Drawing app — pre-installed promotion',
  },
  {
    name: 'Drawboard PDF',
    packageName: 'Drawboard.DrawboardPDF',
    publisher: 'Drawboard',
    category: 'utility',
    description: 'PDF editor — pre-installed promotion',
  },
  {
    name: 'Fitbit',
    packageName: 'Fitbit.FitbitCoach',
    publisher: 'Fitbit',
    category: 'utility',
    description: 'Fitness tracker — pre-installed promotion',
  },
  {
    name: 'PicsArt',
    packageName: 'PicsArt-PhotoStudio.PicsArt-PhotoStudio',
    publisher: 'PicsArt',
    category: 'utility',
    description: 'Photo editor — pre-installed promotion',
  },
  {
    name: 'Amazon',
    packageName: 'AmazonMobileLLC.AmazonShopping',
    publisher: 'Amazon',
    category: 'utility',
    description: 'Shopping app — pre-installed promotion',
  },
  {
    name: 'WinZip',
    packageName: 'WinZipComputing.WinZipUniversal',
    publisher: 'WinZip',
    category: 'utility',
    description: 'Archive tool — free alternatives available',
  },

  // Additional OEM bloatware
  {
    name: 'HP Desktop Support',
    packageName: 'AD2F1837.HPDesktopSupportUtilities',
    publisher: 'HP',
    category: 'oem',
    description: 'HP desktop support utilities',
  },
  {
    name: 'HP Quick Drop',
    packageName: 'AD2F1837.HPQuickDrop',
    publisher: 'HP',
    category: 'oem',
    description: 'HP file transfer tool — runs background services',
  },
  {
    name: 'HP System Information',
    packageName: 'AD2F1837.HPSystemInformation',
    publisher: 'HP',
    category: 'oem',
    description: 'HP system info tool — redundant with Windows',
  },
  {
    name: 'HP Privacy Settings',
    packageName: 'AD2F1837.HPPrivacySettings',
    publisher: 'HP',
    category: 'oem',
    description: 'HP privacy configuration tool',
  },
  {
    name: 'HP Support Assistant',
    packageName: 'AD2F1837.HPSupportAssistant',
    publisher: 'HP',
    category: 'oem',
    description: 'HP support tool — heavy on resources and notifications',
  },
  {
    name: 'HP Easy Clean',
    packageName: 'AD2F1837.HPEasyClean',
    publisher: 'HP',
    category: 'oem',
    description: 'HP keyboard lock for cleaning',
  },
  {
    name: 'HP Sure Shield AI',
    packageName: 'AD2F1837.HPSureShieldAI',
    publisher: 'HP',
    category: 'oem',
    description: 'HP AI-based security — redundant with Windows Defender',
  },
  {
    name: 'HP AI Experience Center',
    packageName: 'AD2F1837.HPAIExperienceCenter',
    publisher: 'HP',
    category: 'oem',
    description: 'HP AI features hub',
  },
  {
    name: 'HP WorkWell',
    packageName: 'AD2F1837.HPWorkWell',
    publisher: 'HP',
    category: 'oem',
    description: 'HP wellness and productivity tracker',
  },
  {
    name: 'HP Power Manager',
    packageName: 'AD2F1837.HPPowerManager',
    publisher: 'HP',
    category: 'oem',
    description: 'HP battery management tool',
  },
  {
    name: 'myHP',
    packageName: 'AD2F1837.myHP',
    publisher: 'HP',
    category: 'oem',
    description: 'HP account and device management',
  },
  {
    name: 'Dell Mobile Connect',
    packageName: 'DellInc.DellMobileConnect',
    publisher: 'Dell',
    category: 'oem',
    description: 'Dell phone integration — runs background services',
  },
  {
    name: 'Lenovo Vantage Service',
    packageName: 'E046963F.LenovoSettingsforEnterprise',
    publisher: 'Lenovo',
    category: 'oem',
    description: 'Lenovo enterprise settings service',
  },

  // ASUS bloatware
  {
    name: 'ASUS Giftbox',
    packageName: 'ASUSTeKCOMPUTERINC.ASUSGiftbox',
    publisher: 'ASUS',
    category: 'oem',
    description: 'ASUS promotional app store with offers',
  },
  {
    name: 'ASUS ScreenXpert',
    packageName: 'ASUSTeKCOMPUTERINC.ScreenXpert',
    publisher: 'ASUS',
    category: 'oem',
    description: 'ASUS ScreenPad control center',
  },
  {
    name: 'ASUS GlideX',
    packageName: 'ASUSTeKCOMPUTERINC.GlideX',
    publisher: 'ASUS',
    category: 'oem',
    description: 'ASUS multi-device screen sharing',
  },
  {
    name: 'ASUS Armoury Crate',
    packageName: 'B9F59455.ASUSArmouryCrate',
    publisher: 'ASUS',
    category: 'oem',
    description: 'ASUS gaming peripheral control — background services',
  },

  // Samsung bloatware
  {
    name: 'Samsung Settings',
    packageName: 'SamsungElectronics.SamsungSettings',
    publisher: 'Samsung',
    category: 'oem',
    description: 'Samsung system settings control panel',
  },
  {
    name: 'Samsung Update',
    packageName: 'SamsungElectronics.SamsungUpdate',
    publisher: 'Samsung',
    category: 'oem',
    description: 'Samsung driver and software updater',
  },
  {
    name: 'Samsung Flow',
    packageName: 'SamsungElectronics.SamsungFlow',
    publisher: 'Samsung',
    category: 'oem',
    description: 'Samsung device connectivity and screen mirroring',
  },
  {
    name: 'Samsung Notes',
    packageName: 'SamsungElectronics.SamsungNotes',
    publisher: 'Samsung',
    category: 'oem',
    description: 'Samsung note-taking app — pre-installed on Galaxy Books',
  },
  {
    name: 'Samsung Security',
    packageName: 'SamsungElectronics.SamsungSecurity',
    publisher: 'Samsung',
    category: 'oem',
    description: 'Samsung security suite — redundant with Windows Defender',
  },
  {
    name: 'Samsung Internet',
    packageName: 'SamsungInternet.SamsungInternet',
    publisher: 'Samsung',
    category: 'oem',
    description: 'Samsung browser — redundant with Edge or Chrome',
  },

  // Acer bloatware
  {
    name: 'Acer Portal',
    packageName: 'AcerIncorporated.AcerPortal',
    publisher: 'Acer',
    category: 'oem',
    description: 'Acer system info and support portal',
  },
  {
    name: 'Acer Collection',
    packageName: 'AcerIncorporated.AcerCollection',
    publisher: 'Acer',
    category: 'oem',
    description: 'Acer recommended app storefront',
  },
  {
    name: 'Acer Jumpstart',
    packageName: 'AcerIncorporated.AcerJumpstart',
    publisher: 'Acer',
    category: 'oem',
    description: 'Acer new device setup and registration',
  },
  {
    name: 'Acer Care Center',
    packageName: 'AcerIncorporated.AcerCareCenter',
    publisher: 'Acer',
    category: 'oem',
    description: 'Acer system diagnostics and warranty checks',
  },

  // MSI bloatware
  {
    name: 'MSI Center',
    packageName: 'MSI.MSICenter',
    publisher: 'MSI',
    category: 'oem',
    description: 'MSI system control and monitoring center',
  },
  {
    name: 'MSI Dragon Center',
    packageName: 'MSI.DragonCenter',
    publisher: 'MSI',
    category: 'oem',
    description: 'MSI gaming optimization suite — heavy background services',
  },
  {
    name: 'MSI True Color',
    packageName: 'MSI.TrueColor',
    publisher: 'MSI',
    category: 'oem',
    description: 'MSI display color calibration tool',
  },

  // Additional OEM/chipset bloatware
  {
    name: 'Intel Driver & Support Assistant',
    packageName: 'INTELCORPORATION.IntelDriverandSupportAssistant',
    publisher: 'Intel',
    category: 'oem',
    description: 'Intel driver updater — runs background services',
  },
  {
    name: 'Realtek Audio Control',
    packageName: 'RealtekSemiconductorCorp.RealtekAudioControl',
    publisher: 'Realtek',
    category: 'oem',
    description: 'Realtek audio manager — can be replaced by third-party EQ',
  },

  // More pre-installed third-party apps
  {
    name: 'Angry Birds 2',
    packageName: 'RovioEntertainmentLtd.AngryBirds2',
    publisher: 'Rovio',
    category: 'gaming',
    description: 'Pre-installed game with microtransactions',
  },
  {
    name: 'Township',
    packageName: 'PlayrixTownship.Township',
    publisher: 'Playrix',
    category: 'gaming',
    description: 'Pre-installed city-building game with microtransactions',
  },
  {
    name: 'Gardenscapes',
    packageName: 'PlayrixGardenscapes.Gardenscapes',
    publisher: 'Playrix',
    category: 'gaming',
    description: 'Pre-installed puzzle game with microtransactions',
  },
  {
    name: 'Royal Match',
    packageName: 'Dream3D.RoyalMatch',
    publisher: 'Dream3D',
    category: 'gaming',
    description: 'Pre-installed puzzle game with microtransactions',
  },
  {
    name: 'World of Tanks Blitz',
    packageName: 'Wargaming.Net.WorldOfTanksBlitz',
    publisher: 'Wargaming',
    category: 'gaming',
    description: 'Pre-installed tank game with microtransactions',
  },
  {
    name: 'Crossout',
    packageName: 'TargemGames.Crossout',
    publisher: 'Targem',
    category: 'gaming',
    description: 'Pre-installed vehicle combat game',
  },
  {
    name: 'Pinterest',
    packageName: 'Pinterest.Pinterest',
    publisher: 'Pinterest',
    category: 'communication',
    description: 'Visual discovery platform — pre-installed promotion',
  },
  {
    name: 'Kahoot!',
    packageName: 'Kahoot.Kahoot',
    publisher: 'Kahoot',
    category: 'utility',
    description: 'Quiz platform — pre-installed promotion',
  },
  {
    name: 'Khan Academy',
    packageName: 'KhanAcademy.KhanAcademy',
    publisher: 'Khan Academy',
    category: 'utility',
    description: 'Educational videos — pre-installed promotion',
  },
  {
    name: 'Grammarly',
    packageName: 'Grammarly.Grammarly',
    publisher: 'Grammarly',
    category: 'utility',
    description: 'Writing assistant — pre-installed promotion',
  },
  {
    name: 'WPS Office',
    packageName: 'KingsoftOffice.WPSOffice',
    publisher: 'Kingsoft',
    category: 'utility',
    description: 'Office suite — pre-installed promotion, free version has ads',
  },
  {
    name: 'Booking.com',
    packageName: 'Booking.Booking',
    publisher: 'Booking Holdings',
    category: 'utility',
    description: 'Travel booking — pre-installed promotion',
  },
  {
    name: 'Tripadvisor',
    packageName: 'Tripadvisor.Tripadvisor',
    publisher: 'Tripadvisor',
    category: 'utility',
    description: 'Travel reviews — pre-installed promotion',
  },
]
