import type { BloatwareApp } from '@shared/types'

export const MS_BLOATWARE: Omit<BloatwareApp, 'id' | 'size' | 'selected'>[] = [
  // Microsoft apps
  {
    name: '3D Viewer',
    packageName: 'Microsoft.Microsoft3DViewer',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: '3D model viewer — rarely used by most users',
  },
  {
    name: 'Bing News',
    packageName: 'Microsoft.BingNews',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'News aggregator with ads',
  },
  {
    name: 'Bing Weather',
    packageName: 'Microsoft.BingWeather',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Weather app with ads',
  },
  {
    name: 'Clipchamp',
    packageName: 'Clipchamp.Clipchamp',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Video editor — promotes paid subscription',
  },
  {
    name: 'Cortana',
    packageName: 'Microsoft.549981C3F5F10',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Voice assistant — uses background resources',
  },
  {
    name: 'Feedback Hub',
    packageName: 'Microsoft.WindowsFeedbackHub',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Feedback submission tool for Windows Insiders',
  },
  {
    name: 'Get Help',
    packageName: 'Microsoft.GetHelp',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Windows help app — links to online support',
  },
  {
    name: 'Mail and Calendar',
    packageName: 'microsoft.windowscommunicationsapps',
    publisher: 'Microsoft',
    category: 'communication',
    description: 'Built-in mail/calendar — most users prefer Outlook or webmail',
  },
  {
    name: 'Maps',
    packageName: 'Microsoft.WindowsMaps',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Windows Maps — most users prefer Google Maps in browser',
  },
  {
    name: 'Microsoft News',
    packageName: 'Microsoft.News',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'News feed with ads and tracking',
  },
  {
    name: 'Microsoft Solitaire',
    packageName: 'Microsoft.MicrosoftSolitaireCollection',
    publisher: 'Microsoft',
    category: 'gaming',
    description: 'Solitaire with ads and Xbox integration',
  },
  {
    name: 'Microsoft Tips',
    packageName: 'Microsoft.Getstarted',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Tips app — promotional content for Microsoft services',
  },
  {
    name: 'Microsoft To Do',
    packageName: 'Microsoft.Todos',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Task management — redundant if using other tools',
  },
  {
    name: 'Mixed Reality Portal',
    packageName: 'Microsoft.MixedReality.Portal',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'VR/AR portal — unnecessary without VR headset',
  },
  {
    name: 'Movies & TV',
    packageName: 'Microsoft.ZuneVideo',
    publisher: 'Microsoft',
    category: 'media',
    description: 'Video player — most users prefer VLC or MPC',
  },
  {
    name: 'Office Hub',
    packageName: 'Microsoft.MicrosoftOfficeHub',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Office promotion hub — not the actual Office suite',
  },
  {
    name: 'OneNote for Windows',
    packageName: 'Microsoft.Office.OneNote',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'OneNote UWP app — desktop version is separate',
  },
  {
    name: 'Outlook (new)',
    packageName: 'Microsoft.OutlookForWindows',
    publisher: 'Microsoft',
    category: 'communication',
    description: 'New Outlook app — replaces Mail, uses web version',
  },
  {
    name: 'Paint',
    packageName: 'Microsoft.MSPaint',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Windows Paint app — remove only if you use a different image editor',
  },
  {
    name: 'People',
    packageName: 'Microsoft.People',
    publisher: 'Microsoft',
    category: 'communication',
    description: 'Contact aggregator — syncs with Microsoft account',
  },
  {
    name: 'Phone Link',
    packageName: 'Microsoft.YourPhone',
    publisher: 'Microsoft',
    category: 'communication',
    description: 'Phone-to-PC app — runs background services',
  },
  {
    name: 'Power Automate',
    packageName: 'Microsoft.PowerAutomateDesktop',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Desktop automation tool — enterprise feature',
  },
  {
    name: 'Quick Assist',
    packageName: 'MicrosoftCorporationII.QuickAssist',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Remote assistance tool',
  },
  {
    name: 'Skype',
    packageName: 'Microsoft.SkypeApp',
    publisher: 'Microsoft',
    category: 'communication',
    description: 'Skype UWP — most users prefer Teams or Discord',
  },
  {
    name: 'Sticky Notes',
    packageName: 'Microsoft.MicrosoftStickyNotes',
    publisher: 'Microsoft',
    category: 'utility',
    description: 'Sticky notes — syncs with Microsoft account',
  },
  {
    name: 'Teams (personal)',
    packageName: 'MSTeams',
    publisher: 'Microsoft',
    category: 'communication',
    description: 'Teams personal edition — auto-starts and runs in background',
  },
  {
    name: 'Voice Recorder',
    packageName: 'Microsoft.WindowsSoundRecorder',
    publisher: 'Microsoft',
    category: 'media',
    description: 'Simple voice recorder',
  },
  {
    name: 'Widgets',
    packageName: 'MicrosoftWindows.Client.WebExperience',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Taskbar widgets — uses Edge WebView and background resources',
  },
  {
    name: 'Xbox App',
    packageName: 'Microsoft.XboxApp',
    publisher: 'Microsoft',
    category: 'gaming',
    description: 'Xbox companion app',
  },
  {
    name: 'Xbox Game Bar',
    packageName: 'Microsoft.XboxGamingOverlay',
    publisher: 'Microsoft',
    category: 'gaming',
    description: 'Game overlay — adds input latency',
  },
  {
    name: 'Xbox Speech to Text',
    packageName: 'Microsoft.XboxSpeechToTextOverlay',
    publisher: 'Microsoft',
    category: 'gaming',
    description: 'Xbox accessibility overlay',
  },
  {
    name: 'Groove Music',
    packageName: 'Microsoft.ZuneMusic',
    publisher: 'Microsoft',
    category: 'media',
    description: 'Music player — deprecated, replaced by Media Player',
  },
  {
    name: 'Bing Search',
    packageName: 'Microsoft.BingSearch',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Bing search integration — web searches from taskbar',
  },
  {
    name: 'Xbox (Gaming App)',
    packageName: 'Microsoft.GamingApp',
    publisher: 'Microsoft',
    category: 'gaming',
    description: 'Xbox PC app for game library and social features',
  },
  {
    name: 'Edge Game Assist',
    packageName: 'Microsoft.Edge.GameAssist',
    publisher: 'Microsoft',
    category: 'gaming',
    description: 'Edge game overlay assistant',
  },
  {
    name: 'Copilot',
    packageName: 'Microsoft.Copilot',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'AI assistant — runs background services and collects data',
  },
  {
    name: 'Microsoft Journal',
    packageName: 'Microsoft.MicrosoftJournal',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Digital journal app — rarely used',
  },
  {
    name: 'Dev Home',
    packageName: 'Microsoft.Windows.DevHome',
    publisher: 'Microsoft',
    category: 'utility',
    description: 'Developer setup tool — unnecessary for most users',
  },
  {
    name: 'Paint 3D',
    packageName: 'Microsoft.MSPaint3D',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: '3D painting app — deprecated by Microsoft',
  },
  {
    name: 'Print 3D',
    packageName: 'Microsoft.Print3D',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: '3D printing app — rarely used',
  },
  {
    name: 'Power BI',
    packageName: 'Microsoft.MicrosoftPowerBIForWindows',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Business analytics — enterprise feature',
  },
  {
    name: 'Sway',
    packageName: 'Microsoft.Office.Sway',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Presentation creator — web-based alternative exists',
  },
  {
    name: 'One Connect',
    packageName: 'Microsoft.OneConnect',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Mobile plan management app',
  },
  {
    name: 'Microsoft 365 Companions',
    packageName: 'Microsoft.Microsoft365Companions',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Microsoft 365 promotional companion app',
  },
  {
    name: 'Network Speed Test',
    packageName: 'Microsoft.NetworkSpeedTest',
    publisher: 'Microsoft',
    category: 'utility',
    description: 'Speed test — web alternatives available',
  },
  {
    name: 'Remote Desktop',
    packageName: 'Microsoft.RemoteDesktop',
    publisher: 'Microsoft',
    category: 'utility',
    description: 'Remote desktop UWP client',
  },
  {
    name: 'Xbox Identity Provider',
    packageName: 'Microsoft.XboxIdentityProvider',
    publisher: 'Microsoft',
    category: 'gaming',
    description: 'Xbox sign-in framework — only needed for Xbox games',
  },
  {
    name: 'Xbox TCUI',
    packageName: 'Microsoft.Xbox.TCUI',
    publisher: 'Microsoft',
    category: 'gaming',
    description: 'Xbox UI framework — only needed for Xbox games',
  },
  {
    name: 'Alarms & Clock',
    packageName: 'Microsoft.WindowsAlarms',
    publisher: 'Microsoft',
    category: 'utility',
    description: 'Alarms and timer app — remove if not needed',
  },
  {
    name: 'PC Manager',
    packageName: 'Microsoft.MicrosoftPCManager',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Ferramenta de otimização — redundante com o DiNho Optimizer',
  },
  {
    name: 'Copilot+ AI Hub',
    packageName: 'Microsoft.Windows.Ai.Copilot.Provider',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'AI hub for Copilot+ PCs — background AI services',
  },
  {
    name: 'Family Safety',
    packageName: 'MicrosoftCorporationII.MicrosoftFamily',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Family safety and parental controls',
  },
  // More Microsoft apps
  {
    name: 'Microsoft Whiteboard',
    packageName: 'Microsoft.Whiteboard',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Digital canvas for team collaboration — rarely used solo',
  },
  {
    name: 'Windows Camera',
    packageName: 'Microsoft.WindowsCamera',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'Built-in webcam app — remove if using third-party camera',
  },
  {
    name: 'Windows Photos',
    packageName: 'Microsoft.Windows.Photos',
    publisher: 'Microsoft',
    category: 'media',
    description: 'Photo viewer/editor — many users prefer alternatives',
  },
  {
    name: 'Steps Recorder',
    packageName: 'Microsoft.StepsRecorder',
    publisher: 'Microsoft',
    category: 'utility',
    description: 'Troubleshooting step recorder — rarely needed',
  },
  {
    name: 'Microsoft Wallet',
    packageName: 'Microsoft.Wallet',
    publisher: 'Microsoft',
    category: 'utility',
    description: 'Digital wallet — US-only, unnecessary elsewhere',
  },
  {
    name: 'Microsoft Messaging',
    packageName: 'Microsoft.Messaging',
    publisher: 'Microsoft',
    category: 'communication',
    description: 'SMS messaging app — requires Phone Link to function',
  },
  {
    name: 'Microsoft Mahjong',
    packageName: 'Microsoft.MicrosoftMahjong',
    publisher: 'Microsoft',
    category: 'gaming',
    description: 'Mahjong game with ads and microtransactions',
  },
  {
    name: 'Microsoft Minesweeper',
    packageName: 'Microsoft.MicrosoftMinesweeper',
    publisher: 'Microsoft',
    category: 'gaming',
    description: 'Minesweeper game with ads and Xbox Live integration',
  },
  {
    name: 'Microsoft Sudoku',
    packageName: 'Microsoft.MicrosoftSudoku',
    publisher: 'Microsoft',
    category: 'gaming',
    description: 'Sudoku game with ads and daily challenges',
  },
  {
    name: 'Microsoft Jigsaw',
    packageName: 'Microsoft.MicrosoftJigsaw',
    publisher: 'Microsoft',
    category: 'gaming',
    description: 'Jigsaw puzzle game with ad-supported content',
  },
  {
    name: 'Windows Recall',
    packageName: 'Microsoft.Windows.Recall',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'AI timeline snapshots — privacy concerns, Copilot+ PCs only',
  },
  {
    name: 'Windows Studio Effects',
    packageName: 'Microsoft.Windows.StudioEffects',
    publisher: 'Microsoft',
    category: 'microsoft',
    description: 'AI camera/audio effects — Copilot+ PC NPU feature',
  },
]
