export {
  clsidExists,
  collectBackupTargets,
  createFullBackup,
  createTargetedBackup,
  execReg,
  expandEnvVars,
  extractExePath,
  findMissingClsidDll,
  fixRegistryEntries,
  pruneOldBackups,
  SAFE_TASK_PATH_RE,
  scanComOle,
  scanNetwork,
  scanPerformance,
  scanRegistry,
  scanScheduledTasks,
  scanSecurity,
  scanSystemHealth,
  splitTaskPath,
  stripRegHeader,
} from './registry-cleaner/index'
