export {
  scanRegistry,
  scanSystemHealth,
  scanComOle,
  scanSecurity,
  scanNetwork,
  scanPerformance,
  scanScheduledTasks,
  fixRegistryEntries,
  collectBackupTargets,
  createFullBackup,
  createTargetedBackup,
  pruneOldBackups,
  execReg,
  splitTaskPath,
  expandEnvVars,
  extractExePath,
  clsidExists,
  findMissingClsidDll,
  stripRegHeader,
  SAFE_TASK_PATH_RE,
} from './registry-cleaner/index'
