import {
  applyChromeExtendedReporting,
  applyChromeFeedback,
  applyChromeMetrics,
  applyEdgeCopilotCdp,
  applyEdgeCopilotPage,
  applyEdgeDiscover,
  applyEdgeMetrics,
  applyEdgePersonalization,
  applyEdgeShopping,
  applyEdgeSidebar,
  applyEdgeSiteInfo,
  applyFirefoxDefaultAgent,
  applyFirefoxTelemetry,
  revertChromeExtendedReporting,
  revertChromeFeedback,
  revertChromeMetrics,
  revertEdgeCopilotCdp,
  revertEdgeCopilotPage,
  revertEdgeDiscover,
  revertEdgeMetrics,
  revertEdgePersonalization,
  revertEdgeShopping,
  revertEdgeSidebar,
  revertEdgeSiteInfo,
  revertFirefoxDefaultAgent,
  revertFirefoxTelemetry,
} from './fixes/browser'
import type { SettingDef } from './helpers'
import {
  applicableChromeExtendedReporting,
  applicableChromeFeedback,
  applicableChromeMetrics,
  applicableFirefoxDefaultAgent,
  applicableFirefoxTelemetry,
  checkChromeExtendedReporting,
  checkChromeFeedback,
  checkChromeMetrics,
  checkEdgeCopilotCdp,
  checkEdgeCopilotPage,
  checkEdgeDiscover,
  checkEdgeMetrics,
  checkEdgePersonalization,
  checkEdgeShopping,
  checkEdgeSidebar,
  checkEdgeSiteInfo,
  checkFirefoxDefaultAgent,
  checkFirefoxTelemetry,
} from './scanners/browser'

export const BROWSER_SETTINGS: SettingDef[] = [
  {
    id: 'edge-metrics',
    category: 'browser',
    label: 'Edge Metrics Reporting',
    description: 'Stop Edge from sending usage and crash metrics to Microsoft',
    requiresAdmin: true,
    check: checkEdgeMetrics,
    apply: applyEdgeMetrics,
    revert: revertEdgeMetrics,
  },
  {
    id: 'edge-site-info',
    category: 'browser',
    label: 'Edge Site Info Collection',
    description: 'Stop Edge from sending site URLs to Microsoft to improve services',
    requiresAdmin: true,
    check: checkEdgeSiteInfo,
    apply: applyEdgeSiteInfo,
    revert: revertEdgeSiteInfo,
  },
  {
    id: 'edge-personalization',
    category: 'browser',
    label: 'Edge Personalization Reporting',
    description: 'Stop Edge from sending browsing history for ad personalization',
    requiresAdmin: true,
    check: checkEdgePersonalization,
    apply: applyEdgePersonalization,
    revert: revertEdgePersonalization,
  },
  {
    id: 'edge-copilot-cdp',
    category: 'browser',
    label: 'Edge Copilot Page Access (CDP)',
    description: 'Prevent Copilot from reading your page content via Chrome DevTools Protocol',
    requiresAdmin: true,
    check: checkEdgeCopilotCdp,
    apply: applyEdgeCopilotCdp,
    revert: revertEdgeCopilotCdp,
  },
  {
    id: 'edge-copilot-page',
    category: 'browser',
    label: 'Edge Copilot Page Context',
    description: 'Prevent Copilot from accessing page context for content analysis',
    requiresAdmin: true,
    check: checkEdgeCopilotPage,
    apply: applyEdgeCopilotPage,
    revert: revertEdgeCopilotPage,
  },
  {
    id: 'edge-discover',
    category: 'browser',
    label: 'Edge Discover Page Scanning',
    description: 'Stop the Discover feature from scanning page content',
    requiresAdmin: true,
    check: checkEdgeDiscover,
    apply: applyEdgeDiscover,
    revert: revertEdgeDiscover,
  },
  {
    id: 'edge-sidebar',
    category: 'browser',
    label: 'Edge Sidebar',
    description: 'Disable the Edge sidebar and its background data collection',
    requiresAdmin: true,
    check: checkEdgeSidebar,
    apply: applyEdgeSidebar,
    revert: revertEdgeSidebar,
  },
  {
    id: 'edge-shopping',
    category: 'browser',
    label: 'Edge Shopping Assistant',
    description: 'Disable the shopping price comparison tracker in Edge',
    requiresAdmin: true,
    check: checkEdgeShopping,
    apply: applyEdgeShopping,
    revert: revertEdgeShopping,
  },
  {
    id: 'chrome-metrics',
    category: 'browser',
    label: 'Chrome Metrics Reporting',
    description: 'Stop Chrome from sending usage and crash metrics to Google',
    requiresAdmin: true,
    check: checkChromeMetrics,
    apply: applyChromeMetrics,
    revert: revertChromeMetrics,
    applicable: applicableChromeMetrics,
  },
  {
    id: 'chrome-feedback',
    category: 'browser',
    label: 'Chrome User Feedback',
    description: 'Prevent Chrome from collecting and sending user feedback data',
    requiresAdmin: true,
    check: checkChromeFeedback,
    apply: applyChromeFeedback,
    revert: revertChromeFeedback,
    applicable: applicableChromeFeedback,
  },
  {
    id: 'chrome-extended-reporting',
    category: 'browser',
    label: 'Chrome Extended Safe Browsing',
    description: 'Stop Chrome from sending extended URL and download reports to Google',
    requiresAdmin: true,
    check: checkChromeExtendedReporting,
    apply: applyChromeExtendedReporting,
    revert: revertChromeExtendedReporting,
    applicable: applicableChromeExtendedReporting,
  },
  {
    id: 'firefox-telemetry',
    category: 'browser',
    label: 'Firefox Telemetry',
    description: 'Disable Firefox telemetry data collection and upload to Mozilla',
    requiresAdmin: true,
    check: checkFirefoxTelemetry,
    apply: applyFirefoxTelemetry,
    revert: revertFirefoxTelemetry,
    applicable: applicableFirefoxTelemetry,
  },
  {
    id: 'firefox-default-agent',
    category: 'browser',
    label: 'Firefox Default Browser Agent',
    description: 'Disable the background agent that reports browser usage data to Mozilla',
    requiresAdmin: true,
    check: checkFirefoxDefaultAgent,
    apply: applyFirefoxDefaultAgent,
    revert: revertFirefoxDefaultAgent,
    applicable: applicableFirefoxDefaultAgent,
  },
]
