import {
  applyAdvertisingId,
  applyLockScreenSpotlight,
  applyPreinstalledApps,
  applySilentlyInstalledApps,
  applyStartSuggestions,
  applySuggestedContent,
  applyTipsNotifications,
  revertAdvertisingId,
  revertLockScreenSpotlight,
  revertPreinstalledApps,
  revertSilentlyInstalledApps,
  revertStartSuggestions,
  revertSuggestedContent,
  revertTipsNotifications,
} from './fixes/ads'
import {
  applyAiServiceAutostart,
  applyClickToDo,
  applyCopilot,
  applyEdgeAiFeatures,
  applyNotepadAi,
  applyPaintAi,
  applyWindowsRecall,
  revertAiServiceAutostart,
  revertClickToDo,
  revertCopilot,
  revertEdgeAiFeatures,
  revertNotepadAi,
  revertPaintAi,
  revertWindowsRecall,
} from './fixes/ai'
import {
  applyBingStartMenu,
  applyBingWebSearch,
  applyCortana,
  applySearchHighlights,
  applyStoreSearchSuggestions,
  revertBingStartMenu,
  revertBingWebSearch,
  revertCortana,
  revertSearchHighlights,
  revertStoreSearchSuggestions,
} from './fixes/search'
import {
  applyServiceDeliveryOptimization,
  applyServiceDiagtrack,
  applyServiceDmwappush,
  applyServiceMapsbroker,
  revertServiceDeliveryOptimization,
  revertServiceDiagtrack,
  revertServiceDmwappush,
  revertServiceMapsbroker,
} from './fixes/services'
import {
  applyClipboardHistory,
  applyClipboardSync,
  applyFindMyDevice,
  applySettingsSync,
  revertClipboardHistory,
  revertClipboardSync,
  revertFindMyDevice,
  revertSettingsSync,
} from './fixes/sync'
import {
  applyTaskAutochkProxy,
  applyTaskCeipConsolidator,
  applyTaskCompatibilityAppraiser,
  applyTaskDiskDiagnostic,
  applyTaskFeedbackDm,
  applyTaskMapsToast,
  applyTaskMapsUpdate,
  applyTaskProgramDataUpdater,
  applyTaskUsbCeip,
  revertTaskAutochkProxy,
  revertTaskCeipConsolidator,
  revertTaskCompatibilityAppraiser,
  revertTaskDiskDiagnostic,
  revertTaskFeedbackDm,
  revertTaskMapsToast,
  revertTaskMapsUpdate,
  revertTaskProgramDataUpdater,
  revertTaskUsbCeip,
} from './fixes/tasks'
import {
  applyActivityHistory,
  applyAppLaunchTracking,
  applyFeedbackFrequency,
  applyHandwritingTelemetry,
  applyInputPersonalization,
  applyPublishActivity,
  applyTailoredExperiences,
  applyTelemetryLevel,
  revertActivityHistory,
  revertAppLaunchTracking,
  revertFeedbackFrequency,
  revertHandwritingTelemetry,
  revertInputPersonalization,
  revertPublishActivity,
  revertTailoredExperiences,
  revertTelemetryLevel,
} from './fixes/telemetry'
import type { SettingDef } from './helpers'
import {
  checkAdvertisingId,
  checkLockScreenSpotlight,
  checkPreinstalledApps,
  checkSilentlyInstalledApps,
  checkStartSuggestions,
  checkSuggestedContent,
  checkTipsNotifications,
} from './scanners/ads'
import {
  applicableAiServiceAutostart,
  checkAiServiceAutostart,
  checkClickToDo,
  checkCopilot,
  checkEdgeAiFeatures,
  checkNotepadAi,
  checkPaintAi,
  checkWindowsRecall,
} from './scanners/ai'
import {
  checkBingStartMenu,
  checkBingWebSearch,
  checkCortana,
  checkSearchHighlights,
  checkStoreSearchSuggestions,
} from './scanners/search'
import {
  applicableServiceDiagtrack,
  applicableServiceDmwappush,
  applicableServiceMapsbroker,
  checkServiceDeliveryOptimization,
  checkServiceDiagtrack,
  checkServiceDmwappush,
  checkServiceMapsbroker,
} from './scanners/services'
import { checkClipboardHistory, checkClipboardSync, checkFindMyDevice, checkSettingsSync } from './scanners/sync'
import {
  applicableTaskAutochkProxy,
  applicableTaskCeipConsolidator,
  applicableTaskCompatibilityAppraiser,
  applicableTaskDiskDiagnostic,
  applicableTaskFeedbackDm,
  applicableTaskMapsToast,
  applicableTaskMapsUpdate,
  applicableTaskProgramDataUpdater,
  applicableTaskUsbCeip,
  checkTaskAutochkProxy,
  checkTaskCeipConsolidator,
  checkTaskCompatibilityAppraiser,
  checkTaskDiskDiagnostic,
  checkTaskFeedbackDm,
  checkTaskMapsToast,
  checkTaskMapsUpdate,
  checkTaskProgramDataUpdater,
  checkTaskUsbCeip,
} from './scanners/tasks'
import {
  checkActivityHistory,
  checkAppLaunchTracking,
  checkFeedbackFrequency,
  checkHandwritingTelemetry,
  checkInputPersonalization,
  checkPublishActivity,
  checkTailoredExperiences,
  checkTelemetryLevel,
} from './scanners/telemetry'
import { BROWSER_SETTINGS } from './browser-settings'

export const SETTINGS: SettingDef[] = [
  {
    id: 'telemetry-level',
    category: 'telemetry',
    label: 'Windows Telemetry',
    description: 'Set diagnostic data collection to minimum (Security level only)',
    requiresAdmin: true,
    check: checkTelemetryLevel,
    apply: applyTelemetryLevel,
    revert: revertTelemetryLevel,
  },
  {
    id: 'activity-history',
    category: 'telemetry',
    label: 'Activity History',
    description: 'Stop Windows from tracking and syncing your app and file usage',
    requiresAdmin: true,
    check: checkActivityHistory,
    apply: applyActivityHistory,
    revert: revertActivityHistory,
  },
  {
    id: 'publish-activity',
    category: 'telemetry',
    label: 'Publish User Activities',
    description: 'Prevent Windows from publishing your activities to Microsoft',
    requiresAdmin: true,
    check: checkPublishActivity,
    apply: applyPublishActivity,
    revert: revertPublishActivity,
  },
  {
    id: 'feedback-frequency',
    category: 'telemetry',
    label: 'Feedback Prompts',
    description: 'Disable periodic Microsoft feedback prompts and surveys',
    requiresAdmin: false,
    check: checkFeedbackFrequency,
    apply: applyFeedbackFrequency,
    revert: revertFeedbackFrequency,
  },
  {
    id: 'handwriting-telemetry',
    category: 'telemetry',
    label: 'Handwriting Data',
    description: 'Stop sending handwriting and typing data to Microsoft',
    requiresAdmin: false,
    check: checkHandwritingTelemetry,
    apply: applyHandwritingTelemetry,
    revert: revertHandwritingTelemetry,
  },
  {
    id: 'input-personalization',
    category: 'telemetry',
    label: 'Input Personalization',
    description: 'Disable typing and inking personalization data collection',
    requiresAdmin: false,
    check: checkInputPersonalization,
    apply: applyInputPersonalization,
    revert: revertInputPersonalization,
  },
  {
    id: 'tailored-experiences',
    category: 'telemetry',
    label: 'Tailored Experiences',
    description: 'Stop Microsoft from using diagnostic data to personalize tips and ads',
    requiresAdmin: false,
    check: checkTailoredExperiences,
    apply: applyTailoredExperiences,
    revert: revertTailoredExperiences,
  },
  {
    id: 'app-launch-tracking',
    category: 'telemetry',
    label: 'App Launch Tracking',
    description: 'Stop Windows from tracking which apps you open to "improve" Start menu',
    requiresAdmin: false,
    check: checkAppLaunchTracking,
    apply: applyAppLaunchTracking,
    revert: revertAppLaunchTracking,
  },
  {
    id: 'advertising-id',
    category: 'ads',
    label: 'Advertising ID',
    description: 'Disable the unique advertising ID that apps use to track you',
    requiresAdmin: false,
    check: checkAdvertisingId,
    apply: applyAdvertisingId,
    revert: revertAdvertisingId,
  },
  {
    id: 'suggested-content',
    category: 'ads',
    label: 'Suggested Content in Settings',
    description: 'Block Microsoft from showing app suggestions and ads in Settings',
    requiresAdmin: false,
    check: checkSuggestedContent,
    apply: applySuggestedContent,
    revert: revertSuggestedContent,
  },
  {
    id: 'tips-notifications',
    category: 'ads',
    label: 'Tips & Suggestions',
    description: 'Disable Windows tips, tricks, and suggestion notifications',
    requiresAdmin: false,
    check: checkTipsNotifications,
    apply: applyTipsNotifications,
    revert: revertTipsNotifications,
  },
  {
    id: 'start-suggestions',
    category: 'ads',
    label: 'Start Menu Suggestions',
    description: 'Disable app suggestions (ads) in the Start menu',
    requiresAdmin: false,
    check: checkStartSuggestions,
    apply: applyStartSuggestions,
    revert: revertStartSuggestions,
  },
  {
    id: 'lock-screen-spotlight',
    category: 'ads',
    label: 'Lock Screen Spotlight',
    description: 'Disable Microsoft Spotlight ads and suggestions on the lock screen',
    requiresAdmin: false,
    check: checkLockScreenSpotlight,
    apply: applyLockScreenSpotlight,
    revert: revertLockScreenSpotlight,
  },
  {
    id: 'silently-installed-apps',
    category: 'ads',
    label: 'Silently Installed Apps',
    description: 'Prevent Windows from automatically installing promoted apps',
    requiresAdmin: false,
    check: checkSilentlyInstalledApps,
    apply: applySilentlyInstalledApps,
    revert: revertSilentlyInstalledApps,
  },
  {
    id: 'preinstalled-apps',
    category: 'ads',
    label: 'Pre-installed App Suggestions',
    description: "Stop Windows from suggesting pre-installed apps you haven't used",
    requiresAdmin: false,
    check: checkPreinstalledApps,
    apply: applyPreinstalledApps,
    revert: revertPreinstalledApps,
  },
  {
    id: 'bing-start-menu',
    category: 'search',
    label: 'Bing in Start Menu',
    description: 'Stop search queries from being sent to Bing via Start menu',
    requiresAdmin: false,
    check: checkBingStartMenu,
    apply: applyBingStartMenu,
    revert: revertBingStartMenu,
  },
  {
    id: 'bing-web-search',
    category: 'search',
    label: 'Bing Web Results',
    description: 'Disable web results in Windows Search — keep searches local only',
    requiresAdmin: false,
    check: checkBingWebSearch,
    apply: applyBingWebSearch,
    revert: revertBingWebSearch,
  },
  {
    id: 'cortana',
    category: 'search',
    label: 'Cortana',
    description: 'Disable Cortana — stops background resource usage and data collection',
    requiresAdmin: true,
    check: checkCortana,
    apply: applyCortana,
    revert: revertCortana,
  },
  {
    id: 'search-highlights',
    category: 'search',
    label: 'Search Highlights',
    description: 'Disable trending search suggestions and web content in search box',
    requiresAdmin: false,
    check: checkSearchHighlights,
    apply: applySearchHighlights,
    revert: revertSearchHighlights,
  },
  {
    id: 'store-search-suggestions',
    category: 'search',
    label: 'Store Search Suggestions',
    description: 'Disable Microsoft Store search suggestions that send queries to Microsoft',
    requiresAdmin: true,
    check: checkStoreSearchSuggestions,
    apply: applyStoreSearchSuggestions,
    revert: revertStoreSearchSuggestions,
  },
  {
    id: 'clipboard-sync',
    category: 'sync',
    label: 'Clipboard Cloud Sync',
    description: 'Prevent clipboard data from being synced across devices via the cloud',
    requiresAdmin: true,
    check: checkClipboardSync,
    apply: applyClipboardSync,
    revert: revertClipboardSync,
  },
  {
    id: 'clipboard-history',
    category: 'sync',
    label: 'Clipboard History',
    description: 'Disable clipboard history that stores copied text and images',
    requiresAdmin: false,
    check: checkClipboardHistory,
    apply: applyClipboardHistory,
    revert: revertClipboardHistory,
  },
  {
    id: 'settings-sync',
    category: 'sync',
    label: 'Settings Sync',
    description: 'Stop syncing Windows settings, themes, and passwords to your Microsoft account',
    requiresAdmin: true,
    check: checkSettingsSync,
    apply: applySettingsSync,
    revert: revertSettingsSync,
  },
  {
    id: 'find-my-device',
    category: 'sync',
    label: 'Find My Device',
    description: 'Disable location-based device tracking by Microsoft',
    requiresAdmin: true,
    check: checkFindMyDevice,
    apply: applyFindMyDevice,
    revert: revertFindMyDevice,
  },
  {
    id: 'copilot',
    category: 'ai',
    label: 'Microsoft Copilot',
    description: 'Disable Microsoft Copilot AI assistant across Windows',
    requiresAdmin: true,
    check: checkCopilot,
    apply: applyCopilot,
    revert: revertCopilot,
  },
  {
    id: 'windows-recall',
    category: 'ai',
    label: 'Windows Recall',
    description: 'Disable Windows Recall AI screenshot history that captures everything on screen',
    requiresAdmin: true,
    check: checkWindowsRecall,
    apply: applyWindowsRecall,
    revert: revertWindowsRecall,
  },
  {
    id: 'click-to-do',
    category: 'ai',
    label: 'Click To Do',
    description: 'Disable Click To Do AI text and image analysis on screen content',
    requiresAdmin: true,
    check: checkClickToDo,
    apply: applyClickToDo,
    revert: revertClickToDo,
  },
  {
    id: 'ai-service-autostart',
    category: 'ai',
    label: 'AI Service Auto-Start',
    description: 'Prevent AI services from automatically starting in the background',
    requiresAdmin: true,
    check: checkAiServiceAutostart,
    apply: applyAiServiceAutostart,
    revert: revertAiServiceAutostart,
    applicable: applicableAiServiceAutostart,
  },
  {
    id: 'edge-ai-features',
    category: 'ai',
    label: 'Edge Compose AI',
    description: 'Disable Edge AI text composition and rewriting features',
    requiresAdmin: true,
    check: checkEdgeAiFeatures,
    apply: applyEdgeAiFeatures,
    revert: revertEdgeAiFeatures,
  },
  {
    id: 'paint-ai',
    category: 'ai',
    label: 'Paint AI Features',
    description: 'Disable AI image generation features in Microsoft Paint',
    requiresAdmin: true,
    check: checkPaintAi,
    apply: applyPaintAi,
    revert: revertPaintAi,
  },
  {
    id: 'notepad-ai',
    category: 'ai',
    label: 'Notepad AI Features',
    description: 'Disable AI text rewriting features in Microsoft Notepad',
    requiresAdmin: true,
    check: checkNotepadAi,
    apply: applyNotepadAi,
    revert: revertNotepadAi,
  },
  {
    id: 'service-diagtrack',
    category: 'services',
    label: 'DiagTrack Service',
    description: 'Disable Connected User Experiences and Telemetry service — not recommended for FiveM/Minecraft',
    requiresAdmin: true,
    check: checkServiceDiagtrack,
    apply: applyServiceDiagtrack,
    revert: revertServiceDiagtrack,
    applicable: applicableServiceDiagtrack,
  },
  {
    id: 'service-dmwappush',
    category: 'services',
    label: 'WAP Push Service',
    description: 'Disable WAP Push Message routing service used for telemetry',
    requiresAdmin: true,
    check: checkServiceDmwappush,
    apply: applyServiceDmwappush,
    revert: revertServiceDmwappush,
    applicable: applicableServiceDmwappush,
  },
  {
    id: 'service-delivery-optimization',
    category: 'services',
    label: 'Delivery Optimization',
    description: 'Disable Windows Update P2P sharing — stops your PC from uploading update data to other devices',
    requiresAdmin: true,
    check: checkServiceDeliveryOptimization,
    apply: applyServiceDeliveryOptimization,
    revert: revertServiceDeliveryOptimization,
  },
  {
    id: 'service-mapsbroker',
    category: 'services',
    label: 'Maps Broker',
    description: 'Disable Downloaded Maps Manager — unnecessary background service',
    requiresAdmin: true,
    check: checkServiceMapsbroker,
    apply: applyServiceMapsbroker,
    revert: revertServiceMapsbroker,
    applicable: applicableServiceMapsbroker,
  },
  {
    id: 'task-compatibility-appraiser',
    category: 'tasks',
    label: 'Compatibility Appraiser',
    description: 'Disable Microsoft telemetry collector for compatibility data',
    requiresAdmin: true,
    check: checkTaskCompatibilityAppraiser,
    apply: applyTaskCompatibilityAppraiser,
    revert: revertTaskCompatibilityAppraiser,
    applicable: applicableTaskCompatibilityAppraiser,
  },
  {
    id: 'task-program-data-updater',
    category: 'tasks',
    label: 'Program Data Updater',
    description: 'Disable background program telemetry upload task',
    requiresAdmin: true,
    check: checkTaskProgramDataUpdater,
    apply: applyTaskProgramDataUpdater,
    revert: revertTaskProgramDataUpdater,
    applicable: applicableTaskProgramDataUpdater,
  },
  {
    id: 'task-autochk-proxy',
    category: 'tasks',
    label: 'Autochk Proxy',
    description: 'Disable telemetry data collection via autochk proxy',
    requiresAdmin: true,
    check: checkTaskAutochkProxy,
    apply: applyTaskAutochkProxy,
    revert: revertTaskAutochkProxy,
    applicable: applicableTaskAutochkProxy,
  },
  {
    id: 'task-ceip-consolidator',
    category: 'tasks',
    label: 'CEIP Consolidator',
    description: 'Disable Customer Experience Improvement Program data upload',
    requiresAdmin: true,
    check: checkTaskCeipConsolidator,
    apply: applyTaskCeipConsolidator,
    revert: revertTaskCeipConsolidator,
    applicable: applicableTaskCeipConsolidator,
  },
  {
    id: 'task-usb-ceip',
    category: 'tasks',
    label: 'USB CEIP',
    description: 'Disable USB device usage telemetry collection',
    requiresAdmin: true,
    check: checkTaskUsbCeip,
    apply: applyTaskUsbCeip,
    revert: revertTaskUsbCeip,
    applicable: applicableTaskUsbCeip,
  },
  {
    id: 'task-disk-diagnostic',
    category: 'tasks',
    label: 'Disk Diagnostic Collector',
    description: 'Disable disk diagnostic data collection and upload',
    requiresAdmin: true,
    check: checkTaskDiskDiagnostic,
    apply: applyTaskDiskDiagnostic,
    revert: revertTaskDiskDiagnostic,
    applicable: applicableTaskDiskDiagnostic,
  },
  {
    id: 'task-feedback-dm',
    category: 'tasks',
    label: 'Feedback DM Client',
    description: 'Disable feedback device management telemetry task',
    requiresAdmin: true,
    check: checkTaskFeedbackDm,
    apply: applyTaskFeedbackDm,
    revert: revertTaskFeedbackDm,
    applicable: applicableTaskFeedbackDm,
  },
  {
    id: 'task-maps-update',
    category: 'tasks',
    label: 'Maps Update Task',
    description: 'Disable automatic map data downloads in the background',
    requiresAdmin: true,
    check: checkTaskMapsUpdate,
    apply: applyTaskMapsUpdate,
    revert: revertTaskMapsUpdate,
    applicable: applicableTaskMapsUpdate,
  },
  {
    id: 'task-maps-toast',
    category: 'tasks',
    label: 'Maps Toast Task',
    description: 'Disable Maps notification task',
    requiresAdmin: true,
    check: checkTaskMapsToast,
    apply: applyTaskMapsToast,
    revert: revertTaskMapsToast,
    applicable: applicableTaskMapsToast,
  },
  ...BROWSER_SETTINGS,
]
