import type { WindowsTweakDef } from '@shared/types'

export const GAMING_SYSTEM_TWEAKS: WindowsTweakDef[] = [
  // ── Gaming ──
  {
    id: 'gamedvr-enabled',
    name: 'Game DVR — OFF',
    description: 'Desativa gravação de gameplay em segundo plano (Game DVR)',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'System\\GameConfigStore',
    key: 'GameDVR_Enabled',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'gamedvr-fse',
    name: 'Game DVR FSE Behavior — 2',
    description: 'Ativa modo exclusivo em tela cheia para jogos',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'System\\GameConfigStore',
    key: 'GameDVR_FSEBehaviorMode',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 2,
  },
  {
    id: 'gamedvr-honor-fse',
    name: 'Game DVR Honor FSE — 1',
    description: 'Respeita escolha de modo exclusivo em tela cheia do usuário',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'System\\GameConfigStore',
    key: 'GameDVR_HonorUserFSEBehaviorMode',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
  },
  {
    id: 'gamedvr-dxgi',
    name: 'Game DVR DXGI FSE — 1',
    description: 'Permite DXGI em modo exclusivo de tela cheia',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'System\\GameConfigStore',
    key: 'GameDVR_DXGIHonorFSEWindowsCompatible',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
  },
  {
    id: 'gamedvr-efse',
    name: 'Game DVR EFSE Flags — 0',
    description: 'Desativa flags experimentais do Game DVR',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'System\\GameConfigStore',
    key: 'GameDVR_EFSEFeatureFlags',
    kind: 'DWord',
    defaultValue: 3,
    optimizedValue: 0,
  },
  {
    id: 'app-capture-off',
    name: 'App Capture — OFF',
    description: 'Desativa captura de aplicativos em segundo plano',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR',
    key: 'AppCaptureEnabled',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'gamedvr-policy',
    name: 'Allow GameDVR (Policy) — 0',
    description: 'Desativa GameDVR via política de grupo (HKLM)',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR',
    key: 'AllowGameDVR',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'gamedvr-pm',
    name: 'Allow GameDVR (PolicyManager) — 0',
    description: 'Desativa GameDVR via PolicyManager (força política)',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\PolicyManager\\default\\ApplicationManagement\\AllowGameDVR',
    key: 'value',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'auto-game-mode',
    name: 'Auto Game Mode — ON',
    description: 'Ativa Game Mode automático do Windows',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\GameBar',
    key: 'AutoGameModeEnabled',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
  },
  {
    id: 'allow-auto-game-mode',
    name: 'Allow Auto Game Mode — ON',
    description: 'Permite ativação automática do Game Mode',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\GameBar',
    key: 'AllowAutoGameMode',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
  },
  {
    id: 'perfopt-csgo',
    name: 'CPU Priority — CS2 (High)',
    description: 'Força prioridade Alta para o processo CS2.exe',
    category: 'gaming',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\cs2.exe\\PerfOptions',
    key: 'CpuPriorityClass',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 3,
  },
  {
    id: 'perfopt-fivem',
    name: 'CPU Priority — FiveM (High)',
    description: 'Força prioridade Alta para o processo FiveM.exe',
    category: 'gaming',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\FiveM.exe\\PerfOptions',
    key: 'CpuPriorityClass',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 3,
  },

  // ── System — performance ──
  {
    id: 'win32-priority-sep',
    name: 'Win32 Priority Separation — 38',
    description: 'Ajusta separação de prioridade para melhor desempenho em jogos',
    category: 'system',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\PriorityControl',
    key: 'Win32PrioritySeparation',
    kind: 'DWord',
    defaultValue: 26,
    optimizedValue: 38,
  },
  {
    id: 'system-responsiveness',
    name: 'System Responsiveness — 0',
    description: 'Remove reserva de CPU para tarefas secundárias',
    category: 'system',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile',
    key: 'SystemResponsiveness',
    kind: 'DWord',
    defaultValue: 20,
    optimizedValue: 0,
  },
  {
    id: 'disable-paging-exec',
    name: 'Disable Paging Executive — 1',
    description: 'Mantém drivers do kernel fixos na RAM (sem swap para disco)',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management',
    key: 'DisablePagingExecutive',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
  {
    id: 'svchost-threshold',
    name: 'SvcHost Split Threshold — 64MB',
    description: 'Aumenta limite de split de serviços para 64MB',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control',
    key: 'SvcHostSplitThresholdInKB',
    kind: 'DWord',
    defaultValue: 3670016,
    optimizedValue: 67108864,
  },
  {
    id: 'ntfs-last-access-off',
    name: 'NTFS Last Access Update — OFF',
    description: 'Desativa atualização de data de último acesso no NTFS',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\FileSystem',
    key: 'NtfsDisableLastAccessUpdate',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
  {
    id: 'wait-to-kill-timeout',
    name: 'WaitToKillServiceTimeout — 2000ms',
    description: 'Reduz timeout de fechamento de serviços para 2s (desliga mais rápido)',
    category: 'system',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Desktop',
    key: 'WaitToKillServiceTimeout',
    kind: 'String',
    defaultValue: '5000',
    optimizedValue: '2000',
    needsLogoff: true,
  },
  {
    id: 'pool-usage-maximum',
    name: 'PoolUsageMaximum — 80%',
    description: 'Aumenta pool do kernel para 80% (mais drivers em RAM, menos swap)',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management',
    key: 'PoolUsageMaximum',
    kind: 'DWord',
    defaultValue: 40,
    optimizedValue: 80,
    needsReboot: true,
  },
  {
    id: 'large-system-cache',
    name: 'LargeSystemCache — ON',
    description: 'Ativa cache grande de sistema (mais assets em RAM)',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management',
    key: 'LargeSystemCache',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
  {
    id: 'hid-power-management',
    name: 'HID Power Save — OFF',
    description: 'Desativa economia de energia de mouse/teclado USB',
    category: 'system',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Services\\HidUsb\\Parameters',
    key: 'DisableIdlePowerManagement',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
  {
    id: 'ntfs-8dot3-disable',
    name: 'NTFS 8.3 Names — OFF',
    description: 'Desativa criação de nomes 8.3 no NTFS (reduz I/O)',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\FileSystem',
    key: 'NtfsDisable8dot3NameCreation',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
  {
    id: 'ntfs-mft-zone',
    name: 'NTFS MFT Zone — 400MB',
    description: 'Aumenta reserva da MFT para 400MB (menos fragmentação)',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\FileSystem',
    key: 'NtfsMftZoneReservation',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 2,
    needsReboot: true,
  },
  {
    id: 'ntfs-tunnel-off',
    name: 'NTFS Tunneling — OFF',
    description: 'Desativa tunelamento NTFS (reduz metadados desnecessários)',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\FileSystem',
    key: 'NtfsDisableTunneling',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
]
