import type { WindowsTweakDef } from '@shared/types'

export const MMCSS_ENERGY_TWEAKS: WindowsTweakDef[] = [
  // ── MMCSS ──
  {
    id: 'mmcss-gpu-priority',
    name: 'MMCSS GPU Priority — 8',
    description: 'Prioridade da GPU em jogos via MMCSS',
    category: 'mmcss',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'GPU Priority',
    kind: 'DWord',
    defaultValue: 2,
    optimizedValue: 8,
  },
  {
    id: 'mmcss-priority',
    name: 'MMCSS CPU Priority — 6',
    description: 'Prioridade da CPU em jogos via MMCSS',
    category: 'mmcss',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'Priority',
    kind: 'DWord',
    defaultValue: 2,
    optimizedValue: 6,
  },
  {
    id: 'mmcss-sched-cat',
    name: 'MMCSS Scheduling Category — High',
    description: 'Categoria de agendamento Alta para jogos',
    category: 'mmcss',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'Scheduling Category',
    kind: 'String',
    defaultValue: 'Medium',
    optimizedValue: 'High',
  },
  {
    id: 'mmcss-sfio',
    name: 'MMCSS SFIO Priority — High',
    description: 'Prioridade de I/O Alta para jogos',
    category: 'mmcss',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'SFIO Priority',
    kind: 'String',
    defaultValue: 'Normal',
    optimizedValue: 'High',
  },
  {
    id: 'mmcss-background',
    name: 'MMCSS Background Only — False',
    description: 'Impede que jogos sejam tratados como tarefa em segundo plano',
    category: 'mmcss',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'Background Only',
    kind: 'String',
    defaultValue: 'True',
    optimizedValue: 'False',
  },
  {
    id: 'mmcss-affinity',
    name: 'MMCSS Affinity — 0 (todos cores)',
    description: 'Permite que jogos usem todos os núcleos da CPU',
    category: 'mmcss',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'Affinity',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 0,
  },
  {
    id: 'mmcss-clock-rate',
    name: 'MMCSS Clock Rate — 10000 (1ms)',
    description: 'Clock rate de 1ms para jogos (timer mais preciso)',
    category: 'mmcss',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'Clock Rate',
    kind: 'DWord',
    defaultValue: 10000,
    optimizedValue: 10000,
  },
  {
    id: 'mmcss-nolazymode',
    name: 'MMCSS NoLazyMode — ON',
    description: 'Desativa modo lazy do MMCSS (threads de jogos nunca dormem)',
    category: 'mmcss',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'NoLazyMode',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
  },

  // ── Energy ──
  {
    id: 'power-throttling-off',
    name: 'Power Throttling — OFF',
    description: 'Desativa throttling de energia do Windows para processos',
    category: 'energy',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Power\\PowerThrottling',
    key: 'PowerThrottlingOff',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
  {
    id: 'hibernate-off',
    name: 'Hibernação — OFF',
    description: 'Desativa hibernação e deleta arquivo hiberfil.sys',
    category: 'energy',
    level: 'basico',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Power',
    key: 'HibernateEnabled',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'pcie-aspm-off',
    name: 'PCIe ASPM — OFF',
    description: 'Desativa economia de energia PCIe (GPU e NVMe sempre ativos)',
    category: 'energy',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Power\\PowerSettings\\ee19f59b-bb67-4979-a67f-5f16dfc4bcae\\0a717a8c-0a10-4e57-9b23-2b0ad0b32ec8',
    key: 'Default',
    kind: 'DWord',
    defaultValue: 2,
    optimizedValue: 0,
  },
  {
    id: 'usb-selective-suspend-off',
    name: 'USB Selective Suspend — OFF',
    description: 'Desativa suspensão seletiva de dispositivos USB',
    category: 'energy',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Power\\PowerSettings\\2a737441-1930-4402-8d77-b2bebba308a3\\48e6b7a6-50f5-4782-a5d4-53bb8f07e226',
    key: 'Default',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'processor-min-max',
    name: 'CPU Min/Max — 100%',
    description: 'Força CPU sempre a 100% mínimo e máximo (remove economia)',
    category: 'energy',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Power\\PowerSettings\\54533251-82be-4824-96c1-47b60b740d00\\893dee8e-2bef-41e0-89c6-b55d0929964c',
    key: 'Default',
    kind: 'DWord',
    defaultValue: 5,
    optimizedValue: 100,
  },
]
