import type { WindowsTweakDef } from '@shared/types'

export const MOUSE_GPU_TWEAKS: WindowsTweakDef[] = [
  // ── Mouse ──
  {
    id: 'mouse-speed',
    name: 'Mouse 1:1 — Sem aceleração',
    description: 'Desativa aceleração do mouse para movimento 1:1',
    category: 'mouse',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Mouse',
    key: 'MouseSpeed',
    kind: 'String',
    defaultValue: '1',
    optimizedValue: '0',
  },
  {
    id: 'mouse-threshold1',
    name: 'Mouse Threshold 1 — Zero',
    description: 'Zera o limite de aceleração do mouse',
    category: 'mouse',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Mouse',
    key: 'MouseThreshold1',
    kind: 'String',
    defaultValue: '6',
    optimizedValue: '0',
  },
  {
    id: 'mouse-threshold2',
    name: 'Mouse Threshold 2 — Zero',
    description: 'Zera o limite secundário de aceleração do mouse',
    category: 'mouse',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Mouse',
    key: 'MouseThreshold2',
    kind: 'String',
    defaultValue: '10',
    optimizedValue: '0',
  },
  {
    id: 'mouse-hover-time',
    name: 'Mouse Hover Time — 0ms',
    description: 'Remove delay de hover e tooltips do mouse',
    category: 'mouse',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Mouse',
    key: 'MouseHoverTime',
    kind: 'String',
    defaultValue: '400',
    optimizedValue: '0',
  },

  // ── GPU ──
  {
    id: 'hags-on',
    name: 'Hardware GPU Scheduling — ON',
    description: 'Ativa agendamento por hardware da GPU (reduz latência)',
    category: 'gpu',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers',
    key: 'HwSchMode',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 2,
    needsReboot: true,
  },
  {
    id: 'mpo-overlay-minfps',
    name: 'MPO Overlay Min FPS — 0',
    description: 'Remove FPS mínimo de overlays MPO (experimental)',
    category: 'gpu',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows\\Dwm',
    key: 'OverlayMinFPS',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
    experimental: true,
  },
  {
    id: 'vsync-global-off',
    name: 'VSync Global — OFF',
    description: 'Força VSync desligado globalmente em jogos DirectX',
    category: 'gpu',
    level: 'full',
    hive: 'HKEY_CURRENT_USER',
    path: 'SOFTWARE\\Microsoft\\DirectX\\UserGpuPreferences',
    key: 'DirectXUserGlobalSettings',
    kind: 'String',
    defaultValue: 'SwapEffectUpgradeCache=1;',
    optimizedValue: 'VSync=Off;SwapEffectUpgradeCache=1;',
  },
  {
    id: 'hw-accel-wpf',
    name: 'HW Acceleration WPF — ON',
    description: 'Ativa aceleração de hardware em apps WPF (mais desempenho)',
    category: 'gpu',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'SOFTWARE\\Microsoft\\Avalon.Graphics',
    key: 'DisableHWAcceleration',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'gpu-tdr-level',
    name: 'GPU TDR Level — 0 (desligado)',
    description: 'Desativa detecção de Timeout/Recovery da GPU',
    category: 'gpu',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers',
    key: 'TdrLevel',
    kind: 'DWord',
    defaultValue: 3,
    optimizedValue: 0,
    needsReboot: true,
  },
  {
    id: 'gpu-tdr-delay',
    name: 'GPU TDR Delay — 8s',
    description: 'Aumenta timeout de recuperação da GPU para 8s (evita crashes)',
    category: 'gpu',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers',
    key: 'TdrDelay',
    kind: 'DWord',
    defaultValue: 2,
    optimizedValue: 8,
    needsReboot: true,
  },
  {
    id: 'gpu-panel-self-refresh',
    name: 'Panel Self Refresh — OFF',
    description: 'Desativa refresh seletivo do painel (evita micro-stutters)',
    category: 'gpu',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers',
    key: 'DisablePanelSelfRefresh',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
]
