import type { WindowsTweakDef } from '@shared/types'
import type { WindowGetter } from '../../index'

export const PERFORMANCE_TWEAKS: WindowsTweakDef[] = [
  // ── Mouse ──
  {
    id: 'mouse-speed',
    name: 'Mouse 1:1 — Sem aceleração',
    description: 'Desativa aceleração do mouse para movimento 1:1',
    category: 'mouse',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Mouse',
    key: 'MouseSpeed',
    kind: 'String',
    defaultValue: '1',
    optimizedValue: '0',
  },
  {
    id: 'mouse-threshold1',
    name: 'Mouse Threshold 1 — Zero',
    description: 'Zera o limite de aceleração do mouse',
    category: 'mouse',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Mouse',
    key: 'MouseThreshold1',
    kind: 'String',
    defaultValue: '6',
    optimizedValue: '0',
  },
  {
    id: 'mouse-threshold2',
    name: 'Mouse Threshold 2 — Zero',
    description: 'Zera o limite secundário de aceleração do mouse',
    category: 'mouse',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Mouse',
    key: 'MouseThreshold2',
    kind: 'String',
    defaultValue: '10',
    optimizedValue: '0',
  },

  {
    id: 'mouse-hover-time',
    name: 'Mouse Hover Time — 0ms',
    description: 'Remove delay de hover e tooltips do mouse',
    category: 'mouse',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Mouse',
    key: 'MouseHoverTime',
    kind: 'String',
    defaultValue: '400',
    optimizedValue: '0',
  },

  // ── Keyboard ──

  // ── GPU ──
  {
    id: 'hags-on',
    name: 'Hardware GPU Scheduling — ON',
    description: 'Ativa agendamento por hardware da GPU (reduz latência)',
    category: 'gpu',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers',
    key: 'HwSchMode',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 2,
    needsReboot: true,
  },
  {
    id: 'mpo-overlay-minfps',
    name: 'MPO Overlay Min FPS — 0',
    description: 'Remove FPS mínimo de overlays MPO (experimental)',
    category: 'gpu',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows\\Dwm',
    key: 'OverlayMinFPS',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
    experimental: true,
  },
  {
    id: 'vsync-global-off',
    name: 'VSync Global — OFF',
    description: 'Força VSync desligado globalmente em jogos DirectX',
    category: 'gpu',
    level: 'full',
    hive: 'HKEY_CURRENT_USER',
    path: 'SOFTWARE\\Microsoft\\DirectX\\UserGpuPreferences',
    key: 'DirectXUserGlobalSettings',
    kind: 'String',
    defaultValue: 'SwapEffectUpgradeCache=1;',
    optimizedValue: 'VSync=Off;SwapEffectUpgradeCache=1;',
  },
  {
    id: 'hw-accel-wpf',
    name: 'HW Acceleration WPF — ON',
    description: 'Ativa aceleração de hardware em apps WPF (mais desempenho)',
    category: 'gpu',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'SOFTWARE\\Microsoft\\Avalon.Graphics',
    key: 'DisableHWAcceleration',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'gpu-tdr-level',
    name: 'GPU TDR Level — 0 (desligado)',
    description: 'Desativa detecção de Timeout/Recovery da GPU',
    category: 'gpu',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers',
    key: 'TdrLevel',
    kind: 'DWord',
    defaultValue: 3,
    optimizedValue: 0,
    needsReboot: true,
  },
  {
    id: 'gpu-tdr-delay',
    name: 'GPU TDR Delay — 8s',
    description: 'Aumenta timeout de recuperação da GPU para 8s (evita crashes)',
    category: 'gpu',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers',
    key: 'TdrDelay',
    kind: 'DWord',
    defaultValue: 2,
    optimizedValue: 8,
    needsReboot: true,
  },

  {
    id: 'gpu-panel-self-refresh',
    name: 'Panel Self Refresh — OFF',
    description: 'Desativa refresh seletivo do painel (evita micro-stutters)',
    category: 'gpu',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers',
    key: 'DisablePanelSelfRefresh',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },

  // ── MMCSS ──
  {
    id: 'mmcss-gpu-priority',
    name: 'MMCSS GPU Priority — 8',
    description: 'Prioridade da GPU em jogos via MMCSS',
    category: 'mmcss',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'GPU Priority',
    kind: 'DWord',
    defaultValue: 2,
    optimizedValue: 8,
  },
  {
    id: 'mmcss-priority',
    name: 'MMCSS CPU Priority — 6',
    description: 'Prioridade da CPU em jogos via MMCSS',
    category: 'mmcss',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'Priority',
    kind: 'DWord',
    defaultValue: 2,
    optimizedValue: 6,
  },
  {
    id: 'mmcss-sched-cat',
    name: 'MMCSS Scheduling Category — High',
    description: 'Categoria de agendamento Alta para jogos',
    category: 'mmcss',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'Scheduling Category',
    kind: 'String',
    defaultValue: 'Medium',
    optimizedValue: 'High',
  },
  {
    id: 'mmcss-sfio',
    name: 'MMCSS SFIO Priority — High',
    description: 'Prioridade de I/O Alta para jogos',
    category: 'mmcss',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'SFIO Priority',
    kind: 'String',
    defaultValue: 'Normal',
    optimizedValue: 'High',
  },
  {
    id: 'mmcss-background',
    name: 'MMCSS Background Only — False',
    description: 'Impede que jogos sejam tratados como tarefa em segundo plano',
    category: 'mmcss',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'Background Only',
    kind: 'String',
    defaultValue: 'True',
    optimizedValue: 'False',
  },
  {
    id: 'mmcss-affinity',
    name: 'MMCSS Affinity — 0 (todos cores)',
    description: 'Permite que jogos usem todos os núcleos da CPU',
    category: 'mmcss',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'Affinity',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 0,
  },
  {
    id: 'mmcss-clock-rate',
    name: 'MMCSS Clock Rate — 10000 (1ms)',
    description: 'Clock rate de 1ms para jogos (timer mais preciso)',
    category: 'mmcss',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'Clock Rate',
    kind: 'DWord',
    defaultValue: 10000,
    optimizedValue: 10000,
  },
  {
    id: 'mmcss-nolazymode',
    name: 'MMCSS NoLazyMode — ON',
    description: 'Desativa modo lazy do MMCSS (threads de jogos nunca dormem)',
    category: 'mmcss',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games',
    key: 'NoLazyMode',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
  },

  // ── Energy ──
  {
    id: 'power-throttling-off',
    name: 'Power Throttling — OFF',
    description: 'Desativa throttling de energia do Windows para processos',
    category: 'energy',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Power\\PowerThrottling',
    key: 'PowerThrottlingOff',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
  {
    id: 'hibernate-off',
    name: 'Hibernação — OFF',
    description: 'Desativa hibernação e deleta arquivo hiberfil.sys',
    category: 'energy',
    level: 'basico',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Power',
    key: 'HibernateEnabled',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'pcie-aspm-off',
    name: 'PCIe ASPM — OFF',
    description: 'Desativa economia de energia PCIe (GPU e NVMe sempre ativos)',
    category: 'energy',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Power\\PowerSettings\\ee19f59b-bb67-4979-a67f-5f16dfc4bcae\\0a717a8c-0a10-4e57-9b23-2b0ad0b32ec8',
    key: 'Default',
    kind: 'DWord',
    defaultValue: 2,
    optimizedValue: 0,
  },
  {
    id: 'usb-selective-suspend-off',
    name: 'USB Selective Suspend — OFF',
    description: 'Desativa suspensão seletiva de dispositivos USB',
    category: 'energy',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Power\\PowerSettings\\2a737441-1930-4402-8d77-b2bebba308a3\\48e6b7a6-50f5-4782-a5d4-53bb8f07e226',
    key: 'Default',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'processor-min-max',
    name: 'CPU Min/Max — 100%',
    description: 'Força CPU sempre a 100% mínimo e máximo (remove economia)',
    category: 'energy',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Power\\PowerSettings\\54533251-82be-4824-96c1-47b60b740d00\\893dee8e-2bef-41e0-89c6-b55d0929964c',
    key: 'Default',
    kind: 'DWord',
    defaultValue: 5,
    optimizedValue: 100,
  },

  // ── Gaming ──
  {
    id: 'gamedvr-enabled',
    name: 'Game DVR — OFF',
    description: 'Desativa gravação de gameplay em segundo plano (Game DVR)',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'System\\GameConfigStore',
    key: 'GameDVR_Enabled',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'gamedvr-fse',
    name: 'Game DVR FSE Behavior — 2',
    description: 'Ativa modo exclusivo em tela cheia para jogos',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'System\\GameConfigStore',
    key: 'GameDVR_FSEBehaviorMode',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 2,
  },
  {
    id: 'gamedvr-honor-fse',
    name: 'Game DVR Honor FSE — 1',
    description: 'Respeita escolha de modo exclusivo em tela cheia do usuário',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'System\\GameConfigStore',
    key: 'GameDVR_HonorUserFSEBehaviorMode',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
  },
  {
    id: 'gamedvr-dxgi',
    name: 'Game DVR DXGI FSE — 1',
    description: 'Permite DXGI em modo exclusivo de tela cheia',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'System\\GameConfigStore',
    key: 'GameDVR_DXGIHonorFSEWindowsCompatible',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
  },
  {
    id: 'gamedvr-efse',
    name: 'Game DVR EFSE Flags — 0',
    description: 'Desativa flags experimentais do Game DVR',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'System\\GameConfigStore',
    key: 'GameDVR_EFSEFeatureFlags',
    kind: 'DWord',
    defaultValue: 3,
    optimizedValue: 0,
  },
  {
    id: 'app-capture-off',
    name: 'App Capture — OFF',
    description: 'Desativa captura de aplicativos em segundo plano',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR',
    key: 'AppCaptureEnabled',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'gamedvr-policy',
    name: 'Allow GameDVR (Policy) — 0',
    description: 'Desativa GameDVR via política de grupo (HKLM)',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR',
    key: 'AllowGameDVR',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'gamedvr-pm',
    name: 'Allow GameDVR (PolicyManager) — 0',
    description: 'Desativa GameDVR via PolicyManager (força política)',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\PolicyManager\\default\\ApplicationManagement\\AllowGameDVR',
    key: 'value',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'auto-game-mode',
    name: 'Auto Game Mode — ON',
    description: 'Ativa Game Mode automático do Windows',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\GameBar',
    key: 'AutoGameModeEnabled',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
  },
  {
    id: 'allow-auto-game-mode',
    name: 'Allow Auto Game Mode — ON',
    description: 'Permite ativação automática do Game Mode',
    category: 'gaming',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\GameBar',
    key: 'AllowAutoGameMode',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
  },
  {
    id: 'perfopt-csgo',
    name: 'CPU Priority — CS2 (High)',
    description: 'Força prioridade Alta para o processo CS2.exe',
    category: 'gaming',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\cs2.exe\\PerfOptions',
    key: 'CpuPriorityClass',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 3,
  },
  {
    id: 'perfopt-fivem',
    name: 'CPU Priority — FiveM (High)',
    description: 'Força prioridade Alta para o processo FiveM.exe',
    category: 'gaming',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\FiveM.exe\\PerfOptions',
    key: 'CpuPriorityClass',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 3,
  },

  // ── System — performance ──
  {
    id: 'win32-priority-sep',
    name: 'Win32 Priority Separation — 38',
    description: 'Ajusta separação de prioridade para melhor desempenho em jogos',
    category: 'system',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\PriorityControl',
    key: 'Win32PrioritySeparation',
    kind: 'DWord',
    defaultValue: 26,
    optimizedValue: 38,
  },
  {
    id: 'system-responsiveness',
    name: 'System Responsiveness — 0',
    description: 'Remove reserva de CPU para tarefas secundárias',
    category: 'system',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile',
    key: 'SystemResponsiveness',
    kind: 'DWord',
    defaultValue: 20,
    optimizedValue: 0,
  },
  {
    id: 'disable-paging-exec',
    name: 'Disable Paging Executive — 1',
    description: 'Mantém drivers do kernel fixos na RAM (sem swap para disco)',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management',
    key: 'DisablePagingExecutive',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
  {
    id: 'svchost-threshold',
    name: 'SvcHost Split Threshold — 64MB',
    description: 'Aumenta limite de split de serviços para 64MB',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control',
    key: 'SvcHostSplitThresholdInKB',
    kind: 'DWord',
    defaultValue: 3670016,
    optimizedValue: 67108864,
  },
  {
    id: 'ntfs-last-access-off',
    name: 'NTFS Last Access Update — OFF',
    description: 'Desativa atualização de data de último acesso no NTFS',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\FileSystem',
    key: 'NtfsDisableLastAccessUpdate',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
  {
    id: 'wait-to-kill-timeout',
    name: 'WaitToKillServiceTimeout — 2000ms',
    description: 'Reduz timeout de fechamento de serviços para 2s (desliga mais rápido)',
    category: 'system',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Desktop',
    key: 'WaitToKillServiceTimeout',
    kind: 'String',
    defaultValue: '5000',
    optimizedValue: '2000',
    needsLogoff: true,
  },

  {
    id: 'pool-usage-maximum',
    name: 'PoolUsageMaximum — 80%',
    description: 'Aumenta pool do kernel para 80% (mais drivers em RAM, menos swap)',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management',
    key: 'PoolUsageMaximum',
    kind: 'DWord',
    defaultValue: 40,
    optimizedValue: 80,
    needsReboot: true,
  },
  {
    id: 'large-system-cache',
    name: 'LargeSystemCache — ON',
    description: 'Ativa cache grande de sistema (mais assets em RAM)',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management',
    key: 'LargeSystemCache',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
  {
    id: 'hid-power-management',
    name: 'HID Power Save — OFF',
    description: 'Desativa economia de energia de mouse/teclado USB',
    category: 'system',
    level: 'medio',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Services\\HidUsb\\Parameters',
    key: 'DisableIdlePowerManagement',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
  {
    id: 'ntfs-8dot3-disable',
    name: 'NTFS 8.3 Names — OFF',
    description: 'Desativa criação de nomes 8.3 no NTFS (reduz I/O)',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\FileSystem',
    key: 'NtfsDisable8dot3NameCreation',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
  {
    id: 'ntfs-mft-zone',
    name: 'NTFS MFT Zone — 400MB',
    description: 'Aumenta reserva da MFT para 400MB (menos fragmentação)',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\FileSystem',
    key: 'NtfsMftZoneReservation',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 2,
    needsReboot: true,
  },
  {
    id: 'ntfs-tunnel-off',
    name: 'NTFS Tunneling — OFF',
    description: 'Desativa tunelamento NTFS (reduz metadados desnecessários)',
    category: 'system',
    level: 'full',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'SYSTEM\\CurrentControlSet\\Control\\FileSystem',
    key: 'NtfsDisableTunneling',
    kind: 'DWord',
    defaultValue: 0,
    optimizedValue: 1,
    needsReboot: true,
  },
]

export function registerPerformanceTweaks(_getWindow: WindowGetter): void {
  // No performance-specific IPC handlers currently
}
