import type { WindowsTweakDef } from '@shared/types'
import type { WindowGetter } from '../../index'

export const VISUAL_TWEAKS: WindowsTweakDef[] = [
  // Accessibility
  {
    id: 'sticky-keys-off',
    name: 'Sticky Keys — OFF',
    description: 'Desativa Sticky Keys (atalhos fixos do Windows)',
    category: 'accessibility',
    level: 'medio',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Accessibility\\StickyKeys',
    key: 'Flags',
    kind: 'String',
    defaultValue: '510',
    optimizedValue: '506',
  },
  {
    id: 'toggle-keys-off',
    name: 'Toggle Keys — OFF',
    description: 'Desativa Toggle Keys (sinal sonoro ao travar teclas)',
    category: 'accessibility',
    level: 'medio',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Accessibility\\ToggleKeys',
    key: 'Flags',
    kind: 'String',
    defaultValue: '62',
    optimizedValue: '58',
  },
  {
    id: 'filter-keys-off',
    name: 'Filter Keys — OFF',
    description: 'Desativa Filter Keys (ignora teclas rápidas repetidas)',
    category: 'accessibility',
    level: 'medio',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Accessibility\\Keyboard Response',
    key: 'Flags',
    kind: 'String',
    defaultValue: '126',
    optimizedValue: '122',
  },
  {
    id: 'mouse-keys-off',
    name: 'Mouse Keys — OFF',
    description: 'Desativa Mouse Keys (controle do mouse pelo teclado)',
    category: 'accessibility',
    level: 'medio',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Accessibility\\MouseKeys',
    key: 'Flags',
    kind: 'String',
    defaultValue: '62',
    optimizedValue: '0',
  },

  // System — visual/appearance
  {
    id: 'menu-show-delay',
    name: 'Menu Show Delay — 0ms',
    description: 'Remove delay de abertura de menus no Windows',
    category: 'system',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Desktop',
    key: 'MenuShowDelay',
    kind: 'String',
    defaultValue: '400',
    optimizedValue: '0',
  },
  {
    id: 'explorer-delay',
    name: 'Explorer Startup Delay — 0ms',
    description: 'Remove delay de inicialização do Explorer',
    category: 'system',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Serialize',
    key: 'StartupDelayInMSec',
    kind: 'DWord',
    defaultValue: 4000,
    optimizedValue: 0,
  },
  {
    id: 'transparency-off',
    name: 'Transparência — OFF',
    description: 'Desativa transparência do Windows (ganho leve de FPS)',
    category: 'system',
    level: 'full',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize',
    key: 'EnableTransparency',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'widgets-off',
    name: 'Widgets (Win11) — OFF',
    description: 'Remove botão de Widgets da barra de tarefas (Win11)',
    category: 'system',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\Windows\\CurrentVersion\\Feeds',
    key: 'ShellFeedsTaskbarEnabled',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'news-interest-off',
    name: 'News & Interests — OFF',
    description: 'Remove Notícias e Interesses da barra de tarefas',
    category: 'system',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced',
    key: 'TaskbarDa',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'min-animate-off',
    name: 'Animação de Janelas — OFF',
    description: 'Desativa animação de minimizar/maximizar janelas',
    category: 'system',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Control Panel\\Desktop\\WindowMetrics',
    key: 'MinAnimate',
    kind: 'String',
    defaultValue: '1',
    optimizedValue: '0',
  },

  // Privacy — visual
  {
    id: 'start-suggested-content-off',
    name: 'Conteúdo Sugerido no Start — OFF',
    description: 'Remove conteúdo sugerido do Menu Iniciar',
    category: 'privacy',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager',
    key: 'SubscribedContent-338388Enabled',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'recent-files-off',
    name: 'Arquivos Recentes no Start — OFF',
    description: 'Remove arquivos recentes do Menu Iniciar',
    category: 'privacy',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced',
    key: 'Start_TrackDocs',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
  {
    id: 'lock-screen-ads-off',
    name: 'Anúncios Tela Bloqueio — OFF',
    description: 'Desativa anúncios e dicas na tela de bloqueio',
    category: 'privacy',
    level: 'basico',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager',
    key: 'RotatingLockScreenOverlayEnabled',
    kind: 'DWord',
    defaultValue: 1,
    optimizedValue: 0,
  },
]

export function registerVisualTweaks(_getWindow: WindowGetter): void {
  // No visual-specific IPC handlers currently
}
